global:
  scrape_interval: 5s
  evaluation_interval: 5s
rule_files:
  - "alert_rules.yml" 

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 'alertmanager:9093'

scrape_configs:
  - job_name: 'devshop-services'
    static_configs:
      - targets:
          - 'catalogue:3001'
          - 'panier:3002'
          - 'commandes:3003'
          - 'notifications:3004'

  - job_name: 'gateway'
    static_configs:
      - targets: ['gateway:3000']
